[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = 'cancun'

# Enable optimizer with 200 runs
optimizer = true
optimizer_runs = 200
via_ir = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
unichain_sepolia = "https://sepolia.unichain.org"
unichain = "https://unichain-mainnet.g.alchemy.com/v2/cCmdllUM3oiBjOpStn0RrTb8eifa87te"
base = "https://base-mainnet.g.alchemy.com/v2/cCmdllUM3oiBjOpStn0RrTb8eifa87te"

[etherscan]
unichain_sepolia = { key = "${UNISCAN_API_KEY}", url = "https://api-sepolia.uniscan.xyz/api" }
unichain = { key = "${UNISCAN_API_KEY}", url = "https://api.uniscan.xyz/api", chain=130 }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
