[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = 'cancun'
# Set Unichain Sepolia as default network
rpc_url = "https://sepolia.unichain.org"
# Enable optimizer with 200 runs
optimizer = true
optimizer_runs = 200
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
unichain_sepolia = "https://sepolia.unichain.org"

[etherscan]
unichain_sepolia = { key = "${UNISCAN_API_KEY}", url = "https://sepolia.uniscan.xyz/" }

